# ./config.yaml

proxy_location: EveryNode
http_options:
  host: 127.0.0.1
  port: 8001
grpc_options:
  port: 9001
  grpc_servicer_functions: []
logging_config:
  encoding: TEXT
  log_level: DEBUG
  logs_dir: null
  enable_access_log: true
applications:
- name: example
  route_prefix: /example
  import_path: workflows.example.serve:fast_app
  runtime_env:
    env_vars:
      PYTHONPATH: .
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OTEL_SDK_DISABLED: "true"
    pip:
    - crewai==0.105.0
    - ray>=2.6.0
    - langchain-openai>=0.0.2
    - markdown